# Generated by Django 6.0.7 on 2026-07-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_comptable', '0002_comptecomptable_analytique_obligatoire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptecomptable',
            name='requiert_auxiliaire',
            field=models.BooleanField(default=False),
        ),
    ]
