# Generated by Django 6.0.7 on 2026-07-16 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
        ('plan_comptable', '0003_comptecomptable_requiert_auxiliaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptecomptable',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_dossier', to='parametres.dossier'),
        ),
        migrations.AddField(
            model_name='journal',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_dossier', to='parametres.dossier'),
        ),
        migrations.AddField(
            model_name='tiers',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_dossier', to='parametres.dossier'),
        ),
    ]
