# Generated by Django 6.0.7 on 2026-07-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_comptable', '0004_comptecomptable_dossier_journal_dossier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiers',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='tiers_photos/'),
        ),
    ]
