# Generated by Django 6.0.7 on 2026-07-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_comptable', '0005_tiers_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tiers',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
