# Generated by Django 6.0.7 on 2026-07-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloturePeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(help_text='Format YYYY-MM ou YYYY', max_length=7, unique=True)),
                ('centralisation_journaux', models.BooleanField(default=False)),
                ('rapprochement_bancaire', models.BooleanField(default=False)),
                ('inventaire_stocks', models.BooleanField(default=False)),
                ('amortissements_provisions', models.BooleanField(default=False)),
                ('regularisation_charges_produits', models.BooleanField(default=False)),
                ('arrete_comptes_tiers', models.BooleanField(default=False)),
                ('validation_commissaire', models.BooleanField(default=False)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
