# Generated by Django 6.0.7 on 2026-07-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etats_financiers', '0002_clotureperiode_dossier'),
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clotureperiode',
            name='periode',
            field=models.CharField(help_text='Format YYYY-MM ou YYYY', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='clotureperiode',
            unique_together={('periode', 'dossier')},
        ),
    ]
