# Generated by Django 6.0.7 on 2026-07-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobilisation',
            name='methode',
            field=models.CharField(choices=[('lineaire', 'Linéaire'), ('degressive', 'Dégressive'), ('exceptionnelle', 'Exceptionnelle'), ('unites_oeuvre', "Unités d'œuvre")], default='lineaire', max_length=20),
        ),
    ]
