# Generated by Django 6.0.7 on 2026-07-15 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan_comptable', '0003_comptecomptable_requiert_auxiliaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('encaissement', 'Encaissement'), ('decaissement', 'Décaissement')], max_length=20)),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mode', models.CharField(choices=[('virement', 'Virement Bancaire'), ('especes', 'Espèces (Caisse)'), ('mobile', 'Mobile Money'), ('cheque', 'Chèque')], max_length=20)),
                ('reference', models.CharField(help_text='N° Facture, BL, ou Référence de transaction', max_length=100)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='paiements/justificatifs/')),
                ('memo', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('rapproche', 'Rapproché'), ('lettre', 'Lettré')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('tiers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='plan_comptable.tiers')),
            ],
            options={
                'ordering': ['-date', '-date_creation'],
            },
        ),
    ]
