# Generated by Django 6.0.7 on 2026-07-16 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_dossier', to='parametres.dossier'),
        ),
    ]
