# Generated by Django 6.0.7 on 2026-07-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
