# Generated by Django 6.0.7 on 2026-07-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_user_nom_user_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Agent', 'Agent'), ('Comptable', 'Comptable'), ('Chef Comptable', 'Chef Comptable'), ('Directeur', 'Directeur'), ('Auditeur', 'Auditeur'), ('Super Admin', 'Super Admin')], max_length=50, unique=True)),
                ('permissions', models.JSONField(default=dict)),
            ],
        ),
    ]
