# Generated by Django 6.0.7 on 2026-07-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
