# Generated by Django 6.0.7 on 2026-07-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_alter_user_photo_profil_delete_userprofile'),
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dossiers',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='parametres.dossier', verbose_name='Dossiers assignés'),
        ),
    ]
