# Generated by Django 6.0.7 on 2026-07-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='statut',
            field=models.CharField(choices=[('chargement', 'En Chargement'), ('transit_zambie', 'Transit Zambie'), ('douane_zambie', 'Douane Zambie'), ('douane_rdc', 'Douane RDC'), ('transit_rdc', 'Transit RDC'), ('arrive_sabri', 'Arrivé à Sabri'), ('decharge', 'Déchargé')], default='chargement', max_length=30),
        ),
    ]
