# Generated by Django 6.0.7 on 2026-07-15 08:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0002_alter_camion_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitLogistique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Nom du circuit (ex: Import Zambie -> RDC)', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EtapeCircuit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.PositiveIntegerField(help_text="Position de l'étape dans le circuit (1, 2, 3...)")),
                ('est_finale', models.BooleanField(default=False, help_text='Cochez si cette étape marque la fin du circuit (ex: Déchargé)')),
                ('couleur_badge', models.CharField(default='bg-muted text-muted-foreground', help_text="Classes CSS Tailwind pour l'UI", max_length=50)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='logistique.circuitlogistique')),
            ],
            options={
                'ordering': ['circuit', 'ordre'],
                'unique_together': {('circuit', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifiant', models.CharField(help_text="Plaque d'immatriculation, N° de vol, N° conteneur...", max_length=50)),
                ('responsable', models.CharField(help_text='Chauffeur, Capitaine, etc.', max_length=255)),
                ('transporteur', models.CharField(max_length=255)),
                ('chargement', models.DecimalField(decimal_places=2, help_text='Poids en tonnes ou volume', max_digits=10)),
                ('date_depart', models.DateTimeField(blank=True, null=True)),
                ('date_arrivee', models.DateTimeField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('progression', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('document_reference', models.CharField(blank=True, help_text='BL, LTA, N° Tracking', max_length=100, null=True)),
                ('facture_transport', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('frais_douane', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expeditions', to='logistique.circuitlogistique')),
                ('etape_actuelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expeditions_en_cours', to='logistique.etapecircuit')),
            ],
        ),
        migrations.DeleteModel(
            name='Camion',
        ),
    ]
