# Generated by Django 6.0.7 on 2026-07-13 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_comptable', '0003_comptecomptable_requiert_auxiliaire'),
        ('saisie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligneecriture',
            name='auxiliaire',
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='centre_cout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='tiers_auxiliaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_ecritures', to='plan_comptable.tiers'),
        ),
    ]
