# Generated by Django 6.0.7 on 2026-07-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie', '0002_remove_ligneecriture_auxiliaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecriture',
            name='numero',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ecriture',
            name='piece',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
