# Generated by Django 6.0.7 on 2026-07-15 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapprochement', '0002_rapprochement_delete_lignecompta_and_more'),
        ('saisie', '0003_alter_ecriture_numero_alter_ecriture_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneecriture',
            name='rapprochement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_ecriture', to='rapprochement.rapprochement'),
        ),
    ]
