# Generated by Django 6.0.7 on 2026-07-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie', '0005_ecriture_dossier_ligneecriture_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneecriture',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='justificatifs_comptables/%Y/%m/'),
        ),
    ]
