# Generated by Django 6.0.7 on 2026-07-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie', '0006_ligneecriture_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneecriture',
            name='numero_ligne',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
