# Generated by Django 6.0.7 on 2026-07-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie', '0007_add_numero_ligne_to_ligne_ecriture'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecriture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ecriture',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
