# Generated by Django 6.0.7 on 2026-08-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie', '0008_ecriture_created_at_ecriture_validated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecriture',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
