# Generated by Django 6.0.7 on 2026-08-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie', '0009_ecriture_numero_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneecriture',
            name='devise_origine',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='montant_credit_origine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='montant_debit_origine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='taux_change',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=15),
        ),
    ]
