# Generated by Django 6.0.7 on 2026-07-13 07:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationTerrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_op', models.CharField(choices=[('depense', 'Dépense'), ('recette', 'Recette')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nature', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('has_photo', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('integre', 'Intégré')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
