# Generated by Django 6.0.7 on 2026-07-20 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrain', '0002_operationterrain_dossier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operationterrain',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='justificatifs_terrain/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='operationterrain',
            name='saisie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_terrain', to=settings.AUTH_USER_MODEL),
        ),
    ]
