# Generated by Django 6.0.7 on 2026-08-03 20:31

from django.db import migrations


def update_recette_to_entree(apps, schema_editor):
    OperationTerrain = apps.get_model('terrain', 'OperationTerrain')
    OperationTerrain.objects.filter(type_op='recette').update(type_op='entree')

def reverse_update(apps, schema_editor):
    OperationTerrain = apps.get_model('terrain', 'OperationTerrain')
    OperationTerrain.objects.filter(type_op='entree').update(type_op='recette')

class Migration(migrations.Migration):

    dependencies = [
        ('terrain', '0003_operationterrain_fichier_operationterrain_saisie_par'),
    ]

    operations = [
        migrations.RunPython(update_recette_to_entree, reverse_update),
    ]
