# Generated by Django 6.0.7 on 2026-08-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrain', '0004_auto_20260803_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationterrain',
            name='numero_facture',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='operationterrain',
            name='nature',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='operationterrain',
            name='notes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='operationterrain',
            name='type_op',
            field=models.CharField(choices=[('depense', 'Dépense'), ('entree', 'Entrée')], max_length=20),
        ),
    ]
