# Generated by Django 6.0.7 on 2026-08-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrain', '0005_operationterrain_numero_facture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationterrain',
            name='numero_facture',
            field=models.CharField(max_length=100),
        ),
    ]
