# Generated by Django 6.0.7 on 2026-07-16 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan_comptable', '0003_comptecomptable_requiert_auxiliaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periode', models.CharField(max_length=7)),
                ('jours_travailles', models.IntegerField(default=26)),
                ('mode_paiement', models.CharField(default='virement', max_length=50)),
                ('salaire_base', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('heures_sup', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('primes', models.JSONField(blank=True, default=list)),
                ('cnss_employe', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ipr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avances', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cnss_patronal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('inpp_patronal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('onem_patronal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validé', 'Validé'), ('payé', 'Payé')], default='brouillon', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(limit_choices_to={'type': 'personnel'}, on_delete=django.db.models.deletion.CASCADE, to='plan_comptable.tiers')),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage'), ('CONSULTANT', 'Consultant')], max_length=50)),
                ('salaire_base', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('fonction', models.CharField(max_length=255)),
                ('est_actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(limit_choices_to={'type': 'personnel'}, on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='plan_comptable.tiers')),
            ],
        ),
    ]
