# Generated by Django 6.0.7 on 2026-07-16 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpaie',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_dossier', to='parametres.dossier'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_dossier', to='parametres.dossier'),
        ),
        migrations.AlterField(
            model_name='bulletinpaie',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('paye', 'Payé')], default='brouillon', max_length=20),
        ),
    ]
