# Generated by Django 6.0.7 on 2026-07-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='compteClient',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='compteFournisseur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
