# Generated by Django 6.0.7 on 2026-08-03 20:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0003_exercicecomptable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TauxChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('devise', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('taux', models.DecimalField(decimal_places=6, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('devise', 'date')},
            },
        ),
    ]
