# Generated by Django 6.0.7 on 2026-07-16 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan_comptable', '0003_comptecomptable_requiert_auxiliaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationFiscale',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type_declaration', models.CharField(choices=[('TVA', 'TVA'), ('IPR', 'IPR (Impôt Professionnel sur les Rémunérations)'), ('Acompte IS', 'Acompte Provisionnel IS'), ('Solde IS', 'Solde IS (Impôt sur les Sociétés)'), ('Patente', 'Patente'), ('Autre', 'Autre')], default='TVA', max_length=20)),
                ('periode', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('echeance', models.DateField()),
                ('statut', models.CharField(choices=[('Brouillon', 'Brouillon'), ('En attente', 'En attente'), ('Déclaré et Payé', 'Déclaré et Payé'), ('En retard', 'En retard')], default='Brouillon', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetenueSource',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type_retenue', models.CharField(choices=[('IBP 14%', 'IBP 14%'), ('Loyer 22%', 'Loyer 22%'), ('Autre', 'Autre')], default='IBP 14%', max_length=20)),
                ('date', models.DateField()),
                ('base_calcul', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('Brouillon', 'Brouillon'), ('Prélevé', 'Prélevé'), ("Reversé à l'État", "Reversé à l'État")], default='Prélevé', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('tiers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retenues_fiscales', to='plan_comptable.tiers')),
            ],
        ),
    ]
