# Generated by Django 6.0.7 on 2026-07-19 20:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('critical', 'Critique'), ('urgent', 'Urgente'), ('warning', 'Avertissement'), ('info', 'Information')], default='info', max_length=20)),
                ('module', models.CharField(choices=[('comptabilite', 'Comptabilité'), ('ventes', 'Ventes & Facturation'), ('paiements', 'Paiements & Trésorerie'), ('logistique', 'Logistique'), ('terrain', 'Terrain'), ('rh', 'Ressources Humaines'), ('fiscalite', 'Fiscalité'), ('rapprochement', 'Rapprochement Bancaire'), ('immobilisations', 'Immobilisations'), ('cloture', 'Clôture & États Financiers'), ('securite', 'Sécurité & Système')], default='securite', max_length=50)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('lu', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-cree_le'],
            },
        ),
    ]
